import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sticky Stickers",
  description: "Generated by Next.js",
};

export default function PrimaryLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
